services:
  portfolio-db:
    image: postgres:17-alpine
    container_name: portfolio-db
    restart: unless-stopped
    ports:
      - '${POSTGRES_PORT:-5999}:5432'
    volumes:
      - portfolio-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-payload}
      POSTGRES_PORT: ${POSTGRES_PORT:-5999}

  portfolio-pgadmin:
    depends_on:
      - portfolio-db
    image: dpage/pgadmin4:latest
    container_name: portfolio-pgadmin
    restart: unless-stopped
    volumes:
      - portfolio-pgadmin:/var/lib/pgadmin
    ports:
      - '${PGADMIN_ACCESS_PORT:-5050}:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@local.dev}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}

volumes:
  portfolio-db-data:
    driver: local
  portfolio-pgadmin:
    driver: local
